# Generated by Django 3.0.7 on 2020-06-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_author',
            new_name='author',
        ),
    ]
