# Generated by Django 3.0.7 on 2020-06-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200625_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
