# Generated by Django 3.0.7 on 2020-06-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_auto_20200604_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='users_following',
            new_name='following',
        ),
    ]
